FROM ghcr.io/rossvideo/catena:one-of-everything-gRPC-dev

LABEL org.opencontainers.image.url="https://github.com/rossvideo/Catena-deployments"
LABEL org.opencontainers.image.licenses="BSD-3-Clause"
LABEL org.opencontainers.image.title="MXL to NDI Stream Catena gRPC Example"
LABEL org.opencontainers.image.version="mxl2ndi_sink-1.0.0"
LABEL org.opencontainers.image.description="Self contained example for Catena mxl2ndi_sink gRPC module"
LABEL org.opencontainers.image.vendor="Ross Video"
LABEL org.opencontainers.image.ref.name="ubuntu"
LABEL org.opencontainers.image.source="https://github.com/rossvideo/mxl-catena"

COPY . /app/gRPC/mxl2ndi_sink/

ENV CATENA_EXAMPLE=mxl2ndi_sink
ENV LD_LIBRARY_PATH=/app/gRPC/mxl2ndi_sink/mxl:/external/ndi
