services:
  mp42ts:
    image: mp42ts:local
    build: 
      context: dockerfiles/mp42ts
    pull_policy: always
    environment:
      - PORT=3000
      - VIDEOS_DIR=/videos
      - WEB_DIR=/app/web
      - NODE_ENV=development
    volumes:
      - ./dockerfiles/mp42ts/web:/app/web:ro
      - ./dockerfiles/mp42ts/server/src:/app/server/src:ro
      - ./videos:/videos:ro
      - /dev/shm:/dev/shm
    ports:
      - "3000:3000"
    stop_grace_period: 10s
    init: true
    command: ["npm", "run", "dev"]
  # pattern:
  #   image: pattern:local
  #   build:
  #     context: dockerfiles/pattern
  #   pull_policy: always
  #   volumes:
  #     - /dev/shm:/dev/shm
  ts2mxl:
    image: ts2mxl:local
    build:
      context: dockerfiles/ts2mxl
    pull_policy: always
    environment:
      FLOW: 81386976-94f3-47c7-ade7-6fcd733e9eb3
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "6253:6254"
  mxl2ndi:
    image: mxl2ndi:local
    build:
      context: dockerfiles/mxl2ndi
    pull_policy: always
    labels:
      FLOW: 81386976-94f3-47c7-ade7-6fcd733e9eb3
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "6254:6254"
      - "5960-5969:5960-5969"
