services:
  domain:
    image: ubuntu:24.04
    entrypoint: ["mkdir", "-p", "/dev/shm/mxl"]
    volumes:
      - /dev/shm:/dev/shm
  landing:
    image: landing:local
    build:
      context: dockerfiles/landing
    pull_policy: always
    environment:
      - PORT=8080
      - README_PATH=/app/README.md
    volumes:
      - ./README.md:/app/README.md:ro
    ports:
      - "80:8080"
    stop_grace_period: 10s
    init: true
  mp42ts:
    image: mp42ts:local
    build: 
      context: dockerfiles/mp42ts
    pull_policy: always
    depends_on:
      - domain
    environment:
      - PORT=3000
      - VIDEOS_DIR=/videos
      - WEB_DIR=/app/web
      - NODE_ENV=development
    volumes:
      - ./dockerfiles/mp42ts/web:/app/web:ro
      - ./dockerfiles/mp42ts/server/src:/app/server/src:ro
      - ./videos:/videos:ro
      - /dev/shm:/dev/shm
    ports:
      - "3000:3000"
    stop_grace_period: 10s
    init: true
    command: ["npm", "run", "dev"]
  pat2mxl:
    image: pat2mxl:local
    build:
      context: dockerfiles/pat2mxl
    pull_policy: always
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - domain
  ts2mxl:
    image: ts2mxl:local
    build:
      context: dockerfiles/ts2mxl
    pull_policy: always
    environment:
      FLOW: 81386976-94f3-47c7-ade7-6fcd733e9eb3
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "6253:6254"
    depends_on:
      - domain
  mxl2ndi:
    image: mxl2ndi:local
    build:
      context: dockerfiles/mxl2ndi
    pull_policy: always
    labels:
      FLOW: 81386976-94f3-47c7-ade7-6fcd733e9eb3
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "6254:6254"
      - "5960-5969:5960-5969"
    depends_on:
      - domain
