# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: externalobject.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'externalobject.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import param_pb2 as param__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x65xternalobject.proto\x12\x06st2138\x1a\x0bparam.proto\"9\n\x1c\x45xternalObjectRequestPayload\x12\x0c\n\x04slot\x18\x01 \x01(\r\x12\x0b\n\x03oid\x18\x02 \x01(\t\"O\n\x15\x45xternalObjectPayload\x12\x10\n\x08\x63\x61\x63hable\x18\x01 \x01(\x08\x12$\n\x07payload\x18\x02 \x01(\x0b\x32\x13.st2138.DataPayloadB6\n\x1a\x63\x61tena.core.externalobjectB\x14\x45xternalObjectProtosH\x01P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'externalobject_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032catena.core.externalobjectB\024ExternalObjectProtosH\001P\001'
  _globals['_EXTERNALOBJECTREQUESTPAYLOAD']._serialized_start=45
  _globals['_EXTERNALOBJECTREQUESTPAYLOAD']._serialized_end=102
  _globals['_EXTERNALOBJECTPAYLOAD']._serialized_start=104
  _globals['_EXTERNALOBJECTPAYLOAD']._serialized_end=183
# @@protoc_insertion_point(module_scope)
