# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: language.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'language.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elanguage.proto\x12\x06st2138\"z\n\x0cLanguagePack\x12\x0c\n\x04name\x18\x01 \x01(\t\x12.\n\x05words\x18\x02 \x03(\x0b\x32\x1f.st2138.LanguagePack.WordsEntry\x1a,\n\nWordsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x84\x01\n\rLanguagePacks\x12/\n\x05packs\x18\x01 \x03(\x0b\x32 .st2138.LanguagePacks.PacksEntry\x1a\x42\n\nPacksEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.st2138.LanguagePack:\x02\x38\x01\"\x88\x01\n\x0cPolyglotText\x12\x41\n\x0f\x64isplay_strings\x18\x01 \x03(\x0b\x32(.st2138.PolyglotText.DisplayStringsEntry\x1a\x35\n\x13\x44isplayStringsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"a\n\x12\x41\x64\x64LanguagePayload\x12\x0c\n\x04slot\x18\x01 \x01(\r\x12+\n\rlanguage_pack\x18\x02 \x01(\x0b\x32\x14.st2138.LanguagePack\x12\x10\n\x08language\x18\x03 \x01(\t\"<\n\x1aLanguagePackRequestPayload\x12\x0c\n\x04slot\x18\x01 \x01(\r\x12\x10\n\x08language\x18\x02 \x01(\t\"!\n\x0cLanguageList\x12\x11\n\tlanguages\x18\x01 \x03(\t\"\x14\n\x04Slot\x12\x0c\n\x04slot\x18\x01 \x01(\rB*\n\x14\x63\x61tena.core.languageB\x0eLanguageProtosH\x01P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'language_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024catena.core.languageB\016LanguageProtosH\001P\001'
  _globals['_LANGUAGEPACK_WORDSENTRY']._loaded_options = None
  _globals['_LANGUAGEPACK_WORDSENTRY']._serialized_options = b'8\001'
  _globals['_LANGUAGEPACKS_PACKSENTRY']._loaded_options = None
  _globals['_LANGUAGEPACKS_PACKSENTRY']._serialized_options = b'8\001'
  _globals['_POLYGLOTTEXT_DISPLAYSTRINGSENTRY']._loaded_options = None
  _globals['_POLYGLOTTEXT_DISPLAYSTRINGSENTRY']._serialized_options = b'8\001'
  _globals['_LANGUAGEPACK']._serialized_start=26
  _globals['_LANGUAGEPACK']._serialized_end=148
  _globals['_LANGUAGEPACK_WORDSENTRY']._serialized_start=104
  _globals['_LANGUAGEPACK_WORDSENTRY']._serialized_end=148
  _globals['_LANGUAGEPACKS']._serialized_start=151
  _globals['_LANGUAGEPACKS']._serialized_end=283
  _globals['_LANGUAGEPACKS_PACKSENTRY']._serialized_start=217
  _globals['_LANGUAGEPACKS_PACKSENTRY']._serialized_end=283
  _globals['_POLYGLOTTEXT']._serialized_start=286
  _globals['_POLYGLOTTEXT']._serialized_end=422
  _globals['_POLYGLOTTEXT_DISPLAYSTRINGSENTRY']._serialized_start=369
  _globals['_POLYGLOTTEXT_DISPLAYSTRINGSENTRY']._serialized_end=422
  _globals['_ADDLANGUAGEPAYLOAD']._serialized_start=424
  _globals['_ADDLANGUAGEPAYLOAD']._serialized_end=521
  _globals['_LANGUAGEPACKREQUESTPAYLOAD']._serialized_start=523
  _globals['_LANGUAGEPACKREQUESTPAYLOAD']._serialized_end=583
  _globals['_LANGUAGELIST']._serialized_start=585
  _globals['_LANGUAGELIST']._serialized_end=618
  _globals['_SLOT']._serialized_start=620
  _globals['_SLOT']._serialized_end=640
# @@protoc_insertion_point(module_scope)
