# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: menu.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'menu.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import language_pb2 as language__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmenu.proto\x12\x06st2138\x1a\x0elanguage.proto\"\xee\x01\n\x04Menu\x12\"\n\x04name\x18\x01 \x01(\x0b\x32\x14.st2138.PolyglotText\x12\x0e\n\x06hidden\x18\x02 \x01(\x08\x12\x10\n\x08\x64isabled\x18\x03 \x01(\x08\x12\x12\n\nparam_oids\x18\x04 \x03(\t\x12\x14\n\x0c\x63ommand_oids\x18\x05 \x03(\t\x12\x33\n\x0c\x63lient_hints\x18\x06 \x03(\x0b\x32\x1d.st2138.Menu.ClientHintsEntry\x12\r\n\x05order\x18\x07 \x01(\r\x1a\x32\n\x10\x43lientHintsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xa7\x01\n\tMenuGroup\x12\"\n\x04name\x18\x01 \x01(\x0b\x32\x14.st2138.PolyglotText\x12+\n\x05menus\x18\x02 \x03(\x0b\x32\x1c.st2138.MenuGroup.MenusEntry\x12\r\n\x05order\x18\x03 \x01(\r\x1a:\n\nMenusEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1b\n\x05value\x18\x02 \x01(\x0b\x32\x0c.st2138.Menu:\x02\x38\x01\x42\"\n\x10\x63\x61tena.core.menuB\nMenuProtosH\x01P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'menu_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020catena.core.menuB\nMenuProtosH\001P\001'
  _globals['_MENU_CLIENTHINTSENTRY']._loaded_options = None
  _globals['_MENU_CLIENTHINTSENTRY']._serialized_options = b'8\001'
  _globals['_MENUGROUP_MENUSENTRY']._loaded_options = None
  _globals['_MENUGROUP_MENUSENTRY']._serialized_options = b'8\001'
  _globals['_MENU']._serialized_start=39
  _globals['_MENU']._serialized_end=277
  _globals['_MENU_CLIENTHINTSENTRY']._serialized_start=227
  _globals['_MENU_CLIENTHINTSENTRY']._serialized_end=277
  _globals['_MENUGROUP']._serialized_start=280
  _globals['_MENUGROUP']._serialized_end=447
  _globals['_MENUGROUP_MENUSENTRY']._serialized_start=389
  _globals['_MENUGROUP_MENUSENTRY']._serialized_end=447
# @@protoc_insertion_point(module_scope)
