# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import device_pb2 as device__pb2
from . import param_pb2 as param__pb2
from . import language_pb2 as language__pb2
from . import externalobject_pb2 as externalobject__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x06st2138\x1a\x0c\x64\x65vice.proto\x1a\x0bparam.proto\x1a\x0elanguage.proto\x1a\x14\x65xternalobject.proto2\x8e\t\n\rCatenaService\x12H\n\rDeviceRequest\x12\x1c.st2138.DeviceRequestPayload\x1a\x17.st2138.DeviceComponent0\x01\x12\x34\n\x11GetPopulatedSlots\x12\r.st2138.Empty\x1a\x10.st2138.SlotList\x12J\n\x0e\x45xecuteCommand\x12\x1d.st2138.ExecuteCommandPayload\x1a\x17.st2138.CommandResponse0\x01\x12^\n\x15\x45xternalObjectRequest\x12$.st2138.ExternalObjectRequestPayload\x1a\x1d.st2138.ExternalObjectPayload0\x01\x12P\n\x10ParamInfoRequest\x12\x1f.st2138.ParamInfoRequestPayload\x1a\x19.st2138.ParamInfoResponse0\x01\x12\x38\n\x08SetValue\x12\x1d.st2138.SingleSetValuePayload\x1a\r.st2138.Empty\x12\x32\n\x08GetValue\x12\x17.st2138.GetValuePayload\x1a\r.st2138.Value\x12<\n\rMultiSetValue\x12\x1c.st2138.MultiSetValuePayload\x1a\r.st2138.Empty\x12\x63\n\x13UpdateSubscriptions\x12\".st2138.UpdateSubscriptionsPayload\x1a&.st2138.DeviceComponent.ComponentParam0\x01\x12K\n\x08GetParam\x12\x17.st2138.GetParamPayload\x1a&.st2138.DeviceComponent.ComponentParam\x12\x38\n\x07\x43onnect\x12\x16.st2138.ConnectPayload\x1a\x13.st2138.PushUpdates0\x01\x12\x38\n\x0b\x41\x64\x64Language\x12\x1a.st2138.AddLanguagePayload\x1a\r.st2138.Empty\x12h\n\x13LanguagePackRequest\x12\".st2138.LanguagePackRequestPayload\x1a-.st2138.DeviceComponent.ComponentLanguagePack\x12\x33\n\rListLanguages\x12\x0c.st2138.Slot\x1a\x14.st2138.LanguageList\x12\x45\n\x0cRefreshToken\x12\x1b.st2138.RefreshTokenPayload\x1a\x18.st2138.ConnectionStatus\x12G\n\x0cRevokeAccess\x12\x1b.st2138.RevokeAccessPayload\x1a\x1a.st2138.RevocationResponseB%\n\x13\x63\x61tena.core.serviceB\nCatenaCoreH\x01P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023catena.core.serviceB\nCatenaCoreH\001P\001'
  _globals['_CATENASERVICE']._serialized_start=91
  _globals['_CATENASERVICE']._serialized_end=1257
# @@protoc_insertion_point(module_scope)
