# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import device_pb2 as device__pb2
from . import externalobject_pb2 as externalobject__pb2
from . import language_pb2 as language__pb2
from . import param_pb2 as param__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CatenaServiceStub(object):
    """Catena's API 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DeviceRequest = channel.unary_stream(
                '/st2138.CatenaService/DeviceRequest',
                request_serializer=device__pb2.DeviceRequestPayload.SerializeToString,
                response_deserializer=device__pb2.DeviceComponent.FromString,
                _registered_method=True)
        self.GetPopulatedSlots = channel.unary_unary(
                '/st2138.CatenaService/GetPopulatedSlots',
                request_serializer=param__pb2.Empty.SerializeToString,
                response_deserializer=device__pb2.SlotList.FromString,
                _registered_method=True)
        self.ExecuteCommand = channel.unary_stream(
                '/st2138.CatenaService/ExecuteCommand',
                request_serializer=param__pb2.ExecuteCommandPayload.SerializeToString,
                response_deserializer=param__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.ExternalObjectRequest = channel.unary_stream(
                '/st2138.CatenaService/ExternalObjectRequest',
                request_serializer=externalobject__pb2.ExternalObjectRequestPayload.SerializeToString,
                response_deserializer=externalobject__pb2.ExternalObjectPayload.FromString,
                _registered_method=True)
        self.ParamInfoRequest = channel.unary_stream(
                '/st2138.CatenaService/ParamInfoRequest',
                request_serializer=param__pb2.ParamInfoRequestPayload.SerializeToString,
                response_deserializer=param__pb2.ParamInfoResponse.FromString,
                _registered_method=True)
        self.SetValue = channel.unary_unary(
                '/st2138.CatenaService/SetValue',
                request_serializer=param__pb2.SingleSetValuePayload.SerializeToString,
                response_deserializer=param__pb2.Empty.FromString,
                _registered_method=True)
        self.GetValue = channel.unary_unary(
                '/st2138.CatenaService/GetValue',
                request_serializer=param__pb2.GetValuePayload.SerializeToString,
                response_deserializer=param__pb2.Value.FromString,
                _registered_method=True)
        self.MultiSetValue = channel.unary_unary(
                '/st2138.CatenaService/MultiSetValue',
                request_serializer=param__pb2.MultiSetValuePayload.SerializeToString,
                response_deserializer=param__pb2.Empty.FromString,
                _registered_method=True)
        self.UpdateSubscriptions = channel.unary_stream(
                '/st2138.CatenaService/UpdateSubscriptions',
                request_serializer=param__pb2.UpdateSubscriptionsPayload.SerializeToString,
                response_deserializer=device__pb2.DeviceComponent.ComponentParam.FromString,
                _registered_method=True)
        self.GetParam = channel.unary_unary(
                '/st2138.CatenaService/GetParam',
                request_serializer=param__pb2.GetParamPayload.SerializeToString,
                response_deserializer=device__pb2.DeviceComponent.ComponentParam.FromString,
                _registered_method=True)
        self.Connect = channel.unary_stream(
                '/st2138.CatenaService/Connect',
                request_serializer=device__pb2.ConnectPayload.SerializeToString,
                response_deserializer=device__pb2.PushUpdates.FromString,
                _registered_method=True)
        self.AddLanguage = channel.unary_unary(
                '/st2138.CatenaService/AddLanguage',
                request_serializer=language__pb2.AddLanguagePayload.SerializeToString,
                response_deserializer=param__pb2.Empty.FromString,
                _registered_method=True)
        self.LanguagePackRequest = channel.unary_unary(
                '/st2138.CatenaService/LanguagePackRequest',
                request_serializer=language__pb2.LanguagePackRequestPayload.SerializeToString,
                response_deserializer=device__pb2.DeviceComponent.ComponentLanguagePack.FromString,
                _registered_method=True)
        self.ListLanguages = channel.unary_unary(
                '/st2138.CatenaService/ListLanguages',
                request_serializer=language__pb2.Slot.SerializeToString,
                response_deserializer=language__pb2.LanguageList.FromString,
                _registered_method=True)
        self.RefreshToken = channel.unary_unary(
                '/st2138.CatenaService/RefreshToken',
                request_serializer=device__pb2.RefreshTokenPayload.SerializeToString,
                response_deserializer=device__pb2.ConnectionStatus.FromString,
                _registered_method=True)
        self.RevokeAccess = channel.unary_unary(
                '/st2138.CatenaService/RevokeAccess',
                request_serializer=device__pb2.RevokeAccessPayload.SerializeToString,
                response_deserializer=device__pb2.RevocationResponse.FromString,
                _registered_method=True)


class CatenaServiceServicer(object):
    """Catena's API 
    """

    def DeviceRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPopulatedSlots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExternalObjectRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ParamInfoRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MultiSetValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSubscriptions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetParam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Connect(self, request, context):
        """The stream of PushUpdates is open-ended, terminating only when the
        logical connection with the client is terminated. 
        Connected clients should use the RefreshToken RPC to prevent the
        connection from being terminated on token expiry.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddLanguage(self, request, context):
        """Multi-language support 
        Optional capability to allow clients to provide additional language packs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LanguagePackRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLanguages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """Token management RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CatenaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DeviceRequest': grpc.unary_stream_rpc_method_handler(
                    servicer.DeviceRequest,
                    request_deserializer=device__pb2.DeviceRequestPayload.FromString,
                    response_serializer=device__pb2.DeviceComponent.SerializeToString,
            ),
            'GetPopulatedSlots': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPopulatedSlots,
                    request_deserializer=param__pb2.Empty.FromString,
                    response_serializer=device__pb2.SlotList.SerializeToString,
            ),
            'ExecuteCommand': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteCommand,
                    request_deserializer=param__pb2.ExecuteCommandPayload.FromString,
                    response_serializer=param__pb2.CommandResponse.SerializeToString,
            ),
            'ExternalObjectRequest': grpc.unary_stream_rpc_method_handler(
                    servicer.ExternalObjectRequest,
                    request_deserializer=externalobject__pb2.ExternalObjectRequestPayload.FromString,
                    response_serializer=externalobject__pb2.ExternalObjectPayload.SerializeToString,
            ),
            'ParamInfoRequest': grpc.unary_stream_rpc_method_handler(
                    servicer.ParamInfoRequest,
                    request_deserializer=param__pb2.ParamInfoRequestPayload.FromString,
                    response_serializer=param__pb2.ParamInfoResponse.SerializeToString,
            ),
            'SetValue': grpc.unary_unary_rpc_method_handler(
                    servicer.SetValue,
                    request_deserializer=param__pb2.SingleSetValuePayload.FromString,
                    response_serializer=param__pb2.Empty.SerializeToString,
            ),
            'GetValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetValue,
                    request_deserializer=param__pb2.GetValuePayload.FromString,
                    response_serializer=param__pb2.Value.SerializeToString,
            ),
            'MultiSetValue': grpc.unary_unary_rpc_method_handler(
                    servicer.MultiSetValue,
                    request_deserializer=param__pb2.MultiSetValuePayload.FromString,
                    response_serializer=param__pb2.Empty.SerializeToString,
            ),
            'UpdateSubscriptions': grpc.unary_stream_rpc_method_handler(
                    servicer.UpdateSubscriptions,
                    request_deserializer=param__pb2.UpdateSubscriptionsPayload.FromString,
                    response_serializer=device__pb2.DeviceComponent.ComponentParam.SerializeToString,
            ),
            'GetParam': grpc.unary_unary_rpc_method_handler(
                    servicer.GetParam,
                    request_deserializer=param__pb2.GetParamPayload.FromString,
                    response_serializer=device__pb2.DeviceComponent.ComponentParam.SerializeToString,
            ),
            'Connect': grpc.unary_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=device__pb2.ConnectPayload.FromString,
                    response_serializer=device__pb2.PushUpdates.SerializeToString,
            ),
            'AddLanguage': grpc.unary_unary_rpc_method_handler(
                    servicer.AddLanguage,
                    request_deserializer=language__pb2.AddLanguagePayload.FromString,
                    response_serializer=param__pb2.Empty.SerializeToString,
            ),
            'LanguagePackRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.LanguagePackRequest,
                    request_deserializer=language__pb2.LanguagePackRequestPayload.FromString,
                    response_serializer=device__pb2.DeviceComponent.ComponentLanguagePack.SerializeToString,
            ),
            'ListLanguages': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLanguages,
                    request_deserializer=language__pb2.Slot.FromString,
                    response_serializer=language__pb2.LanguageList.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=device__pb2.RefreshTokenPayload.FromString,
                    response_serializer=device__pb2.ConnectionStatus.SerializeToString,
            ),
            'RevokeAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeAccess,
                    request_deserializer=device__pb2.RevokeAccessPayload.FromString,
                    response_serializer=device__pb2.RevocationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'st2138.CatenaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('st2138.CatenaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CatenaService(object):
    """Catena's API 
    """

    @staticmethod
    def DeviceRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/st2138.CatenaService/DeviceRequest',
            device__pb2.DeviceRequestPayload.SerializeToString,
            device__pb2.DeviceComponent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPopulatedSlots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/st2138.CatenaService/GetPopulatedSlots',
            param__pb2.Empty.SerializeToString,
            device__pb2.SlotList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/st2138.CatenaService/ExecuteCommand',
            param__pb2.ExecuteCommandPayload.SerializeToString,
            param__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExternalObjectRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/st2138.CatenaService/ExternalObjectRequest',
            externalobject__pb2.ExternalObjectRequestPayload.SerializeToString,
            externalobject__pb2.ExternalObjectPayload.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ParamInfoRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/st2138.CatenaService/ParamInfoRequest',
            param__pb2.ParamInfoRequestPayload.SerializeToString,
            param__pb2.ParamInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/st2138.CatenaService/SetValue',
            param__pb2.SingleSetValuePayload.SerializeToString,
            param__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/st2138.CatenaService/GetValue',
            param__pb2.GetValuePayload.SerializeToString,
            param__pb2.Value.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MultiSetValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/st2138.CatenaService/MultiSetValue',
            param__pb2.MultiSetValuePayload.SerializeToString,
            param__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSubscriptions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/st2138.CatenaService/UpdateSubscriptions',
            param__pb2.UpdateSubscriptionsPayload.SerializeToString,
            device__pb2.DeviceComponent.ComponentParam.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetParam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/st2138.CatenaService/GetParam',
            param__pb2.GetParamPayload.SerializeToString,
            device__pb2.DeviceComponent.ComponentParam.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/st2138.CatenaService/Connect',
            device__pb2.ConnectPayload.SerializeToString,
            device__pb2.PushUpdates.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddLanguage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/st2138.CatenaService/AddLanguage',
            language__pb2.AddLanguagePayload.SerializeToString,
            param__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LanguagePackRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/st2138.CatenaService/LanguagePackRequest',
            language__pb2.LanguagePackRequestPayload.SerializeToString,
            device__pb2.DeviceComponent.ComponentLanguagePack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLanguages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/st2138.CatenaService/ListLanguages',
            language__pb2.Slot.SerializeToString,
            language__pb2.LanguageList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/st2138.CatenaService/RefreshToken',
            device__pb2.RefreshTokenPayload.SerializeToString,
            device__pb2.ConnectionStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/st2138.CatenaService/RevokeAccess',
            device__pb2.RevokeAccessPayload.SerializeToString,
            device__pb2.RevocationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
