{
 "title": "MXL MV Monitor",
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "FPS",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fps" } },
   "targets": [
    {
     "expr": "Control{instance=\"control:14100\", type=\"fps\"}",
     "legendFormat": "1"
    }
   ]
  },
  {
   "title": "Drops",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "DropsGauge{instance=\"control:14100\"}",
     "legendFormat": "1"
    }
   ]
  },
  {
   "title": "Drops Counter",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "DropsCounter{instance=\"control:14100\"}",
     "legendFormat": "1"
    }
   ]
  },
  { "title": "Control", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Control",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "Control{instance=\"control:14100\", type=\"load\"}",
     "legendFormat": "Control load"
    }
   ]
  },
  { "title": "Inputs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 40, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "Input{instance=\"input1:15100\", type=\"load\"}",
     "legendFormat": "1"
    },
    {
     "expr": "Input{instance=\"input2:15101\", type=\"load\"}",
     "legendFormat": "2"
    },
    {
     "expr": "Input{instance=\"input3:15102\", type=\"load\"}",
     "legendFormat": "3"
    },
    {
     "expr": "Input{instance=\"input4:15103\", type=\"load\"}",
     "legendFormat": "4"
    },
    {
     "expr": "Input{instance=\"input5:15104\", type=\"load\"}",
     "legendFormat": "5"
    },
    {
     "expr": "Input{instance=\"input6:15105\", type=\"load\"}",
     "legendFormat": "6"
    },
    {
     "expr": "Input{instance=\"input7:15106\", type=\"load\"}",
     "legendFormat": "7"
    },
    {
     "expr": "Input{instance=\"input8:15107\", type=\"load\"}",
     "legendFormat": "8"
    },
    {
     "expr": "Input{instance=\"input9:15108\", type=\"load\"}",
     "legendFormat": "9"
    },
    {
     "expr": "Input{instance=\"input10:15109\", type=\"load\"}",
     "legendFormat": "10"
    },
    {
     "expr": "Input{instance=\"input11:15110\", type=\"load\"}",
     "legendFormat": "11"
    },
    {
     "expr": "Input{instance=\"input12:15111\", type=\"load\"}",
     "legendFormat": "12"
    },
    {
     "expr": "Input{instance=\"input13:15112\", type=\"load\"}",
     "legendFormat": "13"
    },
    {
     "expr": "Input{instance=\"input14:15113\", type=\"load\"}",
     "legendFormat": "14"
    },
    {
     "expr": "Input{instance=\"input15:15114\", type=\"load\"}",
     "legendFormat": "15"
    },
    {
     "expr": "Input{instance=\"input16:15115\", type=\"load\"}",
     "legendFormat": "16"
    }
   ]
  },
  {
   "title": "V210 Decode",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 40, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "PixelConverter{instance=\"input1:15100\", type=\"load\"}",
     "legendFormat": "1"
    },
    {
     "expr": "PixelConverter{instance=\"input2:15101\", type=\"load\"}",
     "legendFormat": "2"
    },
    {
     "expr": "PixelConverter{instance=\"input3:15102\", type=\"load\"}",
     "legendFormat": "3"
    },
    {
     "expr": "PixelConverter{instance=\"input4:15103\", type=\"load\"}",
     "legendFormat": "4"
    },
    {
     "expr": "PixelConverter{instance=\"input5:15104\", type=\"load\"}",
     "legendFormat": "5"
    },
    {
     "expr": "PixelConverter{instance=\"input6:15105\", type=\"load\"}",
     "legendFormat": "6"
    },
    {
     "expr": "PixelConverter{instance=\"input7:15106\", type=\"load\"}",
     "legendFormat": "7"
    },
    {
     "expr": "PixelConverter{instance=\"input8:15107\", type=\"load\"}",
     "legendFormat": "8"
    },
    {
     "expr": "PixelConverter{instance=\"input9:15108\", type=\"load\"}",
     "legendFormat": "9"
    },
    {
     "expr": "PixelConverter{instance=\"input10:15109\", type=\"load\"}",
     "legendFormat": "10"
    },
    {
     "expr": "PixelConverter{instance=\"input11:15110\", type=\"load\"}",
     "legendFormat": "11"
    },
    {
     "expr": "PixelConverter{instance=\"input12:15111\", type=\"load\"}",
     "legendFormat": "12"
    },
    {
     "expr": "PixelConverter{instance=\"input13:15112\", type=\"load\"}",
     "legendFormat": "13"
    },
    {
     "expr": "PixelConverter{instance=\"input14:15113\", type=\"load\"}",
     "legendFormat": "14"
    },
    {
     "expr": "PixelConverter{instance=\"input15:15114\", type=\"load\"}",
     "legendFormat": "15"
    },
    {
     "expr": "PixelConverter{instance=\"input16:15115\", type=\"load\"}",
     "legendFormat": "16"
    }
   ]
  },
  {
   "title": "Proxy Creation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 40, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "OutputConverter{instance=\"input1:15100\", type=\"load\"}",
     "legendFormat": "1"
    },
    {
     "expr": "OutputConverter{instance=\"input2:15101\", type=\"load\"}",
     "legendFormat": "2"
    },
    {
     "expr": "OutputConverter{instance=\"input3:15102\", type=\"load\"}",
     "legendFormat": "3"
    },
    {
     "expr": "OutputConverter{instance=\"input4:15103\", type=\"load\"}",
     "legendFormat": "4"
    },
    {
     "expr": "OutputConverter{instance=\"input5:15104\", type=\"load\"}",
     "legendFormat": "5"
    },
    {
     "expr": "OutputConverter{instance=\"input6:15105\", type=\"load\"}",
     "legendFormat": "6"
    },
    {
     "expr": "OutputConverter{instance=\"input7:15106\", type=\"load\"}",
     "legendFormat": "7"
    },
    {
     "expr": "OutputConverter{instance=\"input8:15107\", type=\"load\"}",
     "legendFormat": "8"
    },
    {
     "expr": "OutputConverter{instance=\"input9:15108\", type=\"load\"}",
     "legendFormat": "9"
    },
    {
     "expr": "OutputConverter{instance=\"input10:15109\", type=\"load\"}",
     "legendFormat": "10"
    },
    {
     "expr": "OutputConverter{instance=\"input11:15110\", type=\"load\"}",
     "legendFormat": "11"
    },
    {
     "expr": "OutputConverter{instance=\"input12:15111\", type=\"load\"}",
     "legendFormat": "12"
    },
    {
     "expr": "OutputConverter{instance=\"input13:15112\", type=\"load\"}",
     "legendFormat": "13"
    },
    {
     "expr": "OutputConverter{instance=\"input14:15113\", type=\"load\"}",
     "legendFormat": "14"
    },
    {
     "expr": "OutputConverter{instance=\"input15:15114\", type=\"load\"}",
     "legendFormat": "15"
    },
    {
     "expr": "OutputConverter{instance=\"input16:15115\", type=\"load\"}",
     "legendFormat": "16"
    }
   ]
  },
  { "title": "MV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 } },
  {
   "title": "Transfer",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 40, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "VideoRead{instance=\"multiviewer:19100\", type=\"transfer\", name=\"Src0\"}",
     "legendFormat": "1"
    },
    {
     "expr": "VideoRead{instance=\"multiviewer:19100\", type=\"transfer\", name=\"Src1\"}",
     "legendFormat": "2"
    },
    {
     "expr": "VideoRead{instance=\"multiviewer:19100\", type=\"transfer\", name=\"Src2\"}",
     "legendFormat": "3"
    },
    {
     "expr": "VideoRead{instance=\"multiviewer:19100\", type=\"transfer\", name=\"Src3\"}",
     "legendFormat": "4"
    },
    {
     "expr": "VideoRead{instance=\"multiviewer:19100\", type=\"transfer\", name=\"Src4\"}",
     "legendFormat": "5"
    },
    {
     "expr": "VideoRead{instance=\"multiviewer:19100\", type=\"transfer\", name=\"Src5\"}",
     "legendFormat": "6"
    },
    {
     "expr": "VideoRead{instance=\"multiviewer:19100\", type=\"transfer\", name=\"Src6\"}",
     "legendFormat": "7"
    },
    {
     "expr": "VideoRead{instance=\"multiviewer:19100\", type=\"transfer\", name=\"Src7\"}",
     "legendFormat": "8"
    },
    {
     "expr": "VideoRead{instance=\"multiviewer:19100\", type=\"transfer\", name=\"Src8\"}",
     "legendFormat": "9"
    },
    {
     "expr": "VideoRead{instance=\"multiviewer:19100\", type=\"transfer\", name=\"Src9\"}",
     "legendFormat": "10"
    },
    {
     "expr": "VideoRead{instance=\"multiviewer:19100\", type=\"transfer\", name=\"Src10\"}",
     "legendFormat": "11"
    },
    {
     "expr": "VideoRead{instance=\"multiviewer:19100\", type=\"transfer\", name=\"Src11\"}",
     "legendFormat": "12"
    },
    {
     "expr": "VideoRead{instance=\"multiviewer:19100\", type=\"transfer\", name=\"Src12\"}",
     "legendFormat": "13"
    },
    {
     "expr": "VideoRead{instance=\"multiviewer:19100\", type=\"transfer\", name=\"Src13\"}",
     "legendFormat": "14"
    },
    {
     "expr": "VideoRead{instance=\"multiviewer:19100\", type=\"transfer\", name=\"Src14\"}",
     "legendFormat": "15"
    },
    {
     "expr": "VideoRead{instance=\"multiviewer:19100\", type=\"transfer\", name=\"Src15\"}",
     "legendFormat": "16"
    }
   ]
  },
  {
   "title": "Load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "MultiViewer{instance=\"multiviewer:19100\", type=\"load\"}",
     "legendFormat": "MultiViewer load"
    }
   ]
  },
  { "title": "Output", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 142 } },
  {
   "title": "Transfer",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "VideoRead{instance=\"output:16100\", type=\"transfer\", name=\"Src4\"}",
     "legendFormat": "MV"
    }
   ]
  },
  {
   "title": "Load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "Output{instance=\"output:16100\", type=\"load\"}",
     "legendFormat": "Output load"
    }
   ]
  }
 ]
}